In [5]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [8]:
col_names = ['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree', 'age', 'label']
# load dataset
pima = pd.read_csv("tugas/pima-indians-diabetes.csv", header=None, names=col_names)
print(pima)



     pregnant  glucose  bp  skin  insulin   bmi  pedigree  age  label
0           6      148  72    35        0  33.6     0.627   50      1
1           1       85  66    29        0  26.6     0.351   31      0
2           8      183  64     0        0  23.3     0.672   32      1
3           1       89  66    23       94  28.1     0.167   21      0
4           0      137  40    35      168  43.1     2.288   33      1
..        ...      ...  ..   ...      ...   ...       ...  ...    ...
763        10      101  76    48      180  32.9     0.171   63      0
764         2      122  70    27        0  36.8     0.340   27      0
765         5      121  72    23      112  26.2     0.245   30      0
766         1      126  60     0        0  30.1     0.349   47      1
767         1       93  70    31        0  30.4     0.315   23      0

[768 rows x 9 columns]


In [10]:
#split dataset in features and target variable
feature_cols = ['pregnant', 'insulin', 'bmi', 'age','glucose','bp','pedigree']
x = pima[feature_cols] # Features
y = pima.label # Target variable
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=3)

In [11]:
clf = DecisionTreeClassifier()
clf = DecisionTreeClassifier(criterion="entropy", max_depth=3)
clf = clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.671875


In [15]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd  

boston_dataset = pd.read_csv("tugas/Boston.csv")
boston = pd.DataFrame(boston_dataset)
boston.head()

Unnamed: 0     crim    zn  indus  chas    nox     rm   age     dis  rad  \
0           1  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1   
1           2  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2   
2           3  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2   
3           4  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3   
4           5  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3   

   tax  ptratio   black  lstat  medv  
0  296     15.3  396.90   4.98  24.0  
1  242     17.8  396.90   9.14  21.6  
2  242     17.8  392.83   4.03  34.7  
3  222     18.7  394.63   2.94  33.4  
4  222     18.7  396.90   5.33  36.2

In [18]:
boston['medv'] = boston_dataset['medv']  # Assign the target column
names = boston.columns[:-1]  # Feature names
array = boston.values
X = array[:,0:13]
Y = array[:,13]
print(X)
print(Y)

[[1.0000e+00 6.3200e-03 1.8000e+01 ... 2.9600e+02 1.5300e+01 3.9690e+02]
 [2.0000e+00 2.7310e-02 0.0000e+00 ... 2.4200e+02 1.7800e+01 3.9690e+02]
 [3.0000e+00 2.7290e-02 0.0000e+00 ... 2.4200e+02 1.7800e+01 3.9283e+02]
 ...
 [5.0400e+02 6.0760e-02 0.0000e+00 ... 2.7300e+02 2.1000e+01 3.9690e+02]
 [5.0500e+02 1.0959e-01 0.0000e+00 ... 2.7300e+02 2.1000e+01 3.9345e+02]
 [5.0600e+02 4.7410e-02 0.0000e+00 ... 2.7300e+02 2.1000e+01 3.9690e+02]]
[ 4.98  9.14  4.03  2.94  5.33  5.21 12.43 19.15 29.93 17.1  20.45 13.27
 15.71  8.26 10.26  8.47  6.58 14.67 11.69 11.28 21.02 13.83 18.72 19.88
 16.3  16.51 14.81 17.28 12.8  11.98 22.6  13.04 27.71 18.35 20.34  9.68
 11.41  8.77 10.13  4.32  1.98  4.84  5.81  7.44  9.55 10.21 14.15 18.8
 30.81 16.2  13.45  9.43  5.28  8.43 14.8   4.81  5.77  3.95  6.86  9.22
 13.15 14.44  6.73  9.5   8.05  4.67 10.24  8.1  13.09  8.79  6.72  9.88
  5.52  7.54  6.78  8.94 11.97 10.27 12.34  9.1   5.29  7.22  6.72  7.51
  9.62  6.53 12.86  8.44  5.5   5.7   8.81  8.

In [49]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [50]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=1234)
model = DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                              max_leaf_nodes=50, min_impurity_decrease=0.0,
                              min_samples_leaf=1, min_samples_split=2,
                              min_weight_fraction_leaf=0.0, random_state=None,
                              splitter='best')

ValueError: Found input variables with inconsistent numbers of samples: [569, 506]

In [ ]:
boston['medv'] = boston_dataset['medv'] 

names = boston.columns[:-1]

array = boston.values

X = array[:,0:14]
Y = array[:,14]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=1234)

model = DecisionTreeRegressor(criterion='squared_error', max_depth=None, max_features=None,
                              max_leaf_nodes=50,
                              min_samples_leaf=1,
                              min_samples_split=2)

rt = model.fit(X_train, Y_train)
rt

import random as rnd

rnd.seed(123458)
X_new = X[rnd.randrange(X.shape[0])]
X_new = X_new.reshape(1, 14)  


YHat = model.predict(X_new)


df = pd.DataFrame(X_new, columns=names)
df["Predicted Price"] = YHat
print(df.head(1))

YHat = model.predict(X_test)
print(YHat)


r2 = r2_score(Y_test, YHat)
print("R-Squared = ", r2)

In [51]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import GridSearchCV

In [52]:
bc = datasets.load_breast_cancer()
X = bc.data
y = bc.target

In [53]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1, stratify=y)

In [54]:
pipeline = make_pipeline(StandardScaler(),
                         LogisticRegression(random_state=1))

In [55]:
bgclassifier = BaggingClassifier(base_estimator=pipeline, n_estimators=100,
                                 max_features=8,
                                 max_samples=80,
                                 random_state=1, n_jobs=5)
bgclassifier.fit(X_train, y_train)

C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


BaggingClassifier(base_estimator=Pipeline(steps=[('standardscaler',
                                                  StandardScaler()),
                                                 ('logisticregression',
                                                  LogisticRegression(random_state=1))]),
                  max_features=8, max_samples=80, n_estimators=100, n_jobs=5,
                  random_state=1)

In [39]:
print('Model test Score: %.3f, ' %bgclassifier.score(X_test, y_test),
      'Model training Score: %.3f' %bgclassifier.score(X_train, y_train))

Model test Score: 0.958,  Model training Score: 0.960


Tugas 
1. 

In [40]:
import matplotlib.pyplot as plt
from sklearn.tree import export_graphviz
import graphviz


dot_data = export_graphviz(clf, out_file=None,
                           feature_names=feature_cols,
                           class_names=['0', '1'],
                           filled=True, rounded=True,
                           special_characters=True)

In [41]:
graph = graphviz.Source(dot_data)
graph.render('decision_tree', view=True)

'decision_tree.pdf'

In [43]:
from sklearn.tree import export_text
from sklearn import tree
import graphviz

In [56]:
tree_rules = export_text(model, feature_names=names.tolist())
# print("Decision Tree Rules:\n", tree_rules)
dot_data = tree.export_graphviz(model, out_file=None,
                                feature_names=names.tolist(),
                                filled=True, rounded=True,
                                special_characters=True)
graph = graphviz.Source(dot_data)
graph.render("CART_tree")

'CART_tree.pdf'

In [45]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline

In [46]:
bc = datasets.load_breast_cancer()
X = bc.data
y = bc.target

# Membagi dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1, stratify=y)

# Melakukan pipelining
pipeline = make_pipeline(StandardScaler(),
                        LogisticRegression(random_state=1))

# Latih model Logistic Regression pada data latih
pipeline.fit(X_train, y_train)

# Evaluasi performa model pada data uji dan latih
test_score = pipeline.score(X_test, y_test)
train_score = pipeline.score(X_train, y_train)

print('Model test Score: %.3f, ' % test_score,
      'Model training Score: %.3f' % train_score)

Model test Score: 0.965,  Model training Score: 0.991
